namespace OpenExcel.OfficeOpenXml.Internal
{
    internal static class SchemaInfo
    {
        public static string[] WorksheetChildSequence = new string[] {
                                                       "sheetPr",
                                                       "dimension",
                                                       "sheetViews",
                                                       "sheetFormatPr",
                                                       "cols",
                                                       "sheetData",
                                                       "sheetCalcPr",
                                                       "sheetProtection",
                                                       "protectedRanges",
                                                       "scenarios",
                                                       "autoFilter",
                                                       "sortState",
                                                       "dataConsolidate",
                                                       "customSheetViews",
                                                       "mergeCells",
                                                       "phoneticPr",
                                                       "conditionalFormatting",
                                                       "dataValidations",
                                                       "hyperlinks",
                                                       "printOptions",
                                                       "pageMargins",
                                                       "pageSetup",
                                                       "headerFooter",
                                                       "rowBreaks",
                                                       "colBreaks",
                                                       "customProperties",
                                                       "cellWatches",
                                                       "ignoredErrors",
                                                       "smartTags",
                                                       "drawing",
                                                       "legacyDrawing",
                                                       "legacyDrawingHF",
                                                       "picture",
                                                       "oleObjects",
                                                       "controls",
                                                       "webPublishItems",
                                                       "tableParts",
                                                       "extLst"
                                                      };
    }
}
